apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: leads-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: leads-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/prod/leads-microservice
        property: DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/leads-microservice
        property: DB_PASSWORD
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: secret/prod/leads-microservice
        property: PAYMENT_API_KEY
    - secretKey: PAYMENT_APPLICATION_ID
      remoteRef:
        key: secret/prod/leads-microservice
        property: PAYMENT_APPLICATION_ID
    - secretKey: PAYMENT_WEBHOOK_API_KEY
      remoteRef:
        key: secret/prod/leads-microservice
        property: PAYMENT_WEBHOOK_API_KEY
