apiVersion: v1
kind: Service
metadata:
  name: leads-microservice
  namespace: statex-apps
  labels:
    app: leads-microservice
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: leads-microservice
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400
      name: http
